config/routes.rb
FolioApp::Application.routes.draw do

  namespace :admin do
    resources :sites do
      member do
        post 'sort'
        post 'update_elements'
      end
      resources :previews
      resources :images do
        collection do
          post 'sort'
          post 'move_images'
        end
        member do
          post 'remove'
        end
      end
      
      resources :galleries do
        collection do
          post 'sort'
        end
      end
      resources :gallery_pages 
      resources :pages do
        member do
          post 'add_text_element'
        end
      end
      resources :links 
      resources :elements do
        member do
          post 'remove'
        end
      end
      resources :folders
      resource :setting, only: [:show]
      resource :header, only: [:show] do
        member do
          post 'add_text_element'
        end
      end
      resource :homepage, only: [:show]
      resource :template do
        collection do
          post 'update_template'
        end
      end
      resources :layouts
    end
  end

  resources :sites, only: [:show], :controller => "homepages" do
    resources :pages, only: [:show]  
    resources :galleries, only: [:show] 
  end

  devise_for :users
  match 'users' => 'users#index'
  match 'about' => "static_pages#about"
  root :to => "static_pages#home"

end

app/views/admin/pages/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Page</h3>
</div>

<%= form_for [:admin, @site, @page], :html => { :class => "form-bootstrap-modal" } do |f| %>
<div class="modal-body">
  <% if @page.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

    <ul>
      <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
</div>

<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
</div>

<% end %>

app/views/admin/pages/_right.html.erb
<div class="right-panel">
	<div class="navbar secondary-navbar">
		<ul class="nav">
			<li class="icon_button">
				<a href="#" id="caret">
					<div>
						<div class="icon caret-left"></div>
					</div>
				</a>
			</li>
			<li class="divider-vertical"></li>
		</ul>
		<div class="left secondary-nav-text"> <%= @page.name %></div>
		<ul class="nav pull-right">
			<li class="divider-vertical"></li>
			<li  class="dropdown icon_button">
				<a href="#" id="add_element" class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" data-original-title="Add Element"><div class="icon add"></div> </a>
				<ul class="dropdown-menu">
					<li><%= link_to "Text Element", add_text_element_admin_site_page_path, method: :post, remote: true %></li>
					<li><%= link_to 'Image Element', {controller: 'admin/images', action:'new', page_id:@page.id}, {:remote => true, 'data-toggle' => 'modal', 'data-target' => "#myModal" } %></li> 
				</ul>

			</li>   
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<%= link_to site_page_path(@site, @page),{:target => "_blank"} do %>
				<div id="view" class="" rel="tooltip" data-original-title="View Site">
					<div class="icon view"></div>
				</div>
				<% end %>
			</li>
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<a href="#" class="save-button" rel="tooltip" rel="tooltip" data-original-title="Save">
					<div id="save" class="" >
						<div class="icon save"></div>
					</div>
				</a>
			</li>
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<a href="#" class="" rel="tooltip" data-original-title="Trash" >
					<div id="trash" class="">
						<div class="icon trash"></div>
					</div>
				</a>
			</li>
		</ul>
	</div>


	<div id="tertiary-navbar" class="navbar tertiary-navbar">
		<div class="nav nav-text">
			<form id="object_form" name="object_form">
				<div class="element-input">

					X: <input type="text" value ="0" id="x" name="x" maxlength="5" size="4">
					Y: <input type="text" value ="0" id="y" name="y" maxlength="5" size="4">
					W: <input type="text" value ="0" id="width" name="width" maxlength="5" size="4">
					H: <input type="text" value ="0" id="height" name="height" maxlength="5" size="4">
				</div>
				<button id="update" class="btn myButton" type="button">Update</button>
			</form>

		</div>
		<ul class="nav">
			<li class="divider-vertical divider-gray"></li>
			<li class="dropdown nav-button">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><div class="icon settings"></div> </a>
				<ul class="dropdown-menu">
					<li><a href="#">Move to top</a></li>
					<li><a href="#">Move to bottom</a></li>
				</ul>
			</li>   
			<li class="divider-vertical divider-gray"></li>
		</ul>
		<div class="options">
			<input type="checkbox" id="show-grid" class="largerCheckbox" name="option1" value="true" checked> Show Grid
			<input type="checkbox" id="snap-grid" class="largerCheckbox" name="option1" value="true" checked> Snap to Grid
		</div>
	</div>

  <div id="text-toolbar" class="navbar tertiary-navbar cirkuitSkin hide" style="z-index:100">
		<!-- <div id="myNicPanel" style="width: 625px;" unselectable="on"></div> -->
  </div>
	

	<div class="right-inner">

		<div class="canvas-background"></div>

		<div class="canvas">
			<div class="grid-background"></div>


			
			<div id="page_elements" data-elements-url="<%= update_elements_admin_site_path %>">
				<% @page.elements.each do |element| %>
				<% e = element.child %>

				<div id="element_<%= element.id %>" class="element <%= e.class.name %>" style="width:<%= element.width %>px; height:<%= element.height %>px; left:<%= element.left %>px; top:<%= element.top %>px; z-index:<%= element.z_index %>;">


					<% if e.class.name == "Image" %>
					<div class="image-holder">
						<div class="image-container" style="width:<%= element.image_width %>px; height:<%= element.image_height %>px; left:<%= element.image_left %>px; top:<%= element.image_top %>px;">

							
							<%= image_tag e.image_file_url(:medium).to_s, alt: "Test Image" %>

							<div class="image-resize-border" style="display:none;">
								<div class="lines red hline"></div>
								<div class="lines red hline bottom"></div>
								<div class="lines red vline"></div>
								<div class="lines red vline right"></div>
							</div>

							<div class='image-resize-handles' style="display:none;">
								<div class="ise red ui-resizable-handle handle ui-resizable-se"></div>
								<div class="isw red ui-resizable-handle handle ui-resizable-sw"></div>
								<div class="ine red ui-resizable-handle handle ui-resizable-ne"></div>
								<div class="inw red ui-resizable-handle handle ui-resizable-nw"></div>
							</div>
						</div>
					</div>
					<% elsif e.class.name == "PageText" %>
					<div class="text-container editable" id="text_container_<%= e.id %>" style="<%= e.style %>">
            
					<textarea class="mce_textarea" id="textarea_<%= e.id %>"><%= e.content.html_safe %></textarea></div>
					<div class="grab"></div>

					<% end %>

          
					<div class="resize-border" style="display:none;">
						<div class="lines hline"></div>
						<div class="lines hline bottom"></div>
						<div class="lines vline"></div>
						<div class="lines vline right"></div>
					</div>

					<div class="resizing-box" style="display:none;">	
						<div class="sw ui-resizable-handle handle ui-resizable-sw"></div>
						<div class="ne ui-resizable-handle handle ui-resizable-ne"></div>
						<div class="nw ui-resizable-handle handle ui-resizable-nw"></div>
						<div class="se ui-resizable-handle handle ui-resizable-se"></div>

					</div>

					<% if e.class.name == "Image" %>
					<div class="element_icons">
						<a href="#" class="crop-button"><i class="icon-nav crop"></i></a>
						<%= link_to '<i class="icon-nav menu-settings"></i>'.html_safe, edit_admin_site_image_path(@site, e),:remote => true, 'data-target' => "#myModal" %>
						<%= link_to '<i class="icon-nav menu-close"></i>'.html_safe, remove_admin_site_element_path(@site, element), method: :post, :remote => true %>
					</div>
					<% elsif e.class.name == "PageText" %>
					<div class="element_icons">
						<!-- <%= link_to '<i class="icon-nav pencil"></i>'.html_safe, '#', class: "edit-text-button" %> -->
						<%= link_to '<i class="icon-nav menu-settings"></i>'.html_safe %>
						<%= link_to '<i class="icon-nav menu-close"></i>'.html_safe, remove_admin_site_element_path(@site, element), method: :post, :remote => true %>
					</div>
					<% end %>



				</div>
				
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/admin/pages/index.html.erb
<h1>Listing pages</h1>

<ul>
  <% @pages.each do |page| %>
   
      <li><%= page.name %></li>
  <% end %>
</ul>

<br />

<%= link_to 'New Page', new_admin_site_page_path %>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_site_pages_path %>

app/views/admin/pages/show.js.erb
	tinyMCERemove();
	$('#pjax-container').html('<%= escape_javascript(render :partial => "right") %>');
	document.title = "<%= escape_javascript("#{@page.name}") %>";
	$('#new_image').fileupload('disable');
	resize();
	elementInit();
	tinyMCEInit();