config/routes.rb
FolioApp::Application.routes.draw do

  namespace :admin do
    resources :sites do
      member do
        post 'sort'
        post 'update_elements'
      end
      resources :previews
      resources :images do
        collection do
          post 'sort'
          post 'move_images'
        end
        member do
          post 'remove'
        end
      end
      
      resources :galleries do
        collection do
          post 'sort'
        end
      end
      resources :gallery_pages 
      resources :pages do
        member do
          post 'add_text_element'
        end
      end
      resources :links 
      resources :elements do
        member do
          post 'remove'
        end
      end
      resources :folders
      resource :setting, only: [:show]
      resource :header, only: [:show] do
        member do
          post 'add_text_element'
        end
      end
      resource :homepage, only: [:show]
      resource :template do
        collection do
          post 'update_template'
        end
      end
      resources :layouts
    end
  end

  resources :sites, only: [:show], :controller => "homepages" do
    resources :pages, only: [:show]  
    resources :galleries, only: [:show] 
  end

  devise_for :users
  match 'users' => 'users#index'
  match 'about' => "static_pages#about"
  root :to => "static_pages#home"

end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  slug            :string(255)
#  site_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  gallery_page_id :integer
#

class Gallery < ActiveRecord::Base
  belongs_to :site
  # belongs_to :gallery_page
  has_one :nav_item, :as =>:navable, :dependent => :destroy
  has_many :gallery_assignments, :dependent => :destroy
  has_many :images, :through => :gallery_assignments, :order => 'gallery_assignments.position'
  
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name
  attr_accessible :name, :site_id, :slug, :gallery_page_id
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
	
  before_filter :authenticate_user!
	before_filter :get_site

  def index
    @galleries = @site.galleries
  end

  def show
    @image = Image.new
    @page = Page.new
    @nav_items = @site.nav_items.includes(:navable).nav_scope
    @gallery_items = @site.nav_items.includes(:navable).gallery_scope
    @gallery = @site.galleries.find(params[:id])

    if request.headers['X-PJAX']
      render :layout => false
    else 
      respond_to do |format| 
        format.html { render layout: 'admin_content' }
        format.js {}
      end
    end
  end

  def new
    @gallery = Gallery.new
    render :layout => false
  end

  def edit
    @gallery = @site.galleries.find(params[:id])
    render :layout => false
  end

  def create
    @gallery = @site.galleries.new(params[:gallery])
    if @gallery.save
      # insert new item after the last top level nav item
      n = @site.nav_items.new(navable:@gallery)
      n.nav = false
      if @site.nav_items.gallery_scope.size > 0
        n.position = @site.nav_items.gallery_scope.last.position + 1
      end
      n.save

      redirect_to :back
      #redirect_to admin_site_pages_path, notice: 'Page was successfully created.'   
    else
      render action: "new" 
    end
  end

  def update
    @gallery = @site.galleries.find(params[:id])
    if @gallery.update_attributes(params[:gallery])
      redirect_to admin_site_gallery_path(@site,@gallery) #, notice: 'Gallery was successfully updated.'
    else
      render action: "edit" 
    end
  end

  def destroy
    @gallery = @site.galleries.find(params[:id])
    @gallery.destroy
    redirect_to admin_site_path(@site)
  end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  before_filter :get_site

  def show
  	@nav_items = @site.nav_items.includes(:navable).nav_scope
    @gallery = @site.galleries.find(params[:id])
    render layout: 'site'
  end

  private

  def get_site 
    @site = Site.find(params[:site_id])
  end
  
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/galleries/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel"><%= @gallery.name %></h3>
</div>

<%= form_for [:admin, @site, @gallery] do |f| %>
<div class="modal-body">
  <%= @gallery.name %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  </div>

<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/admin/galleries/_right.html.erb
<div class="right-panel">
	<div class="navbar secondary-navbar">
		<ul class="nav">
			<li class="icon_button">
				<a href="#" id="caret">
					<div>
						<div class="icon caret-left"></div>
					</div>
				</a>
			</li>
			<li class="divider-vertical"></li>
		</ul>
		<div class="left secondary-nav-text"> <%= @gallery.name %></div>
		<ul class="nav pull-right">
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<%= link_to site_gallery_path(@site, @gallery) do %>
				<div id="view" class="" rel="tooltip" data-original-title="View Site">
					<div class="icon view"></div>
				</div>
				<% end %>
			</li>
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<a href="#" class="" rel="tooltip" rel="tooltip" data-original-title="Save">
					<div id="save" class="" >
						<div class="icon save"></div>
					</div>
				</a>
			</li>
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<a href="#" class="" rel="tooltip" data-original-title="Trash" >
					<div id="trash" class="">
						<div class="icon trash"></div>
					</div>
				</a>
			</li>
		</ul>
	</div>
	<div class="right-inner">
		<ul id="sortable" class="thumb_grid" data-move-images-url="<%= move_images_admin_site_images_path(@site) %>" data-gallery-url="<%= admin_site_gallery_path(@site, @gallery) %>" data-gallery_id="<%= @gallery.id %>" data-update-url= "<%= sort_admin_site_images_path(@site) %>">
			<% @gallery.images.each do |image| %>
			<li id="image_<%= image.id %>" class="drop_allowed">
				<div class="thumbnail_border"></div>

				<div class="thumbnail">
					<%= image_tag image.image_file_url(:thumb).to_s %>
				</div>

				<div class="image_icons">
					<%= link_to '<i class="icon-nav menu-settings"></i>'.html_safe, edit_admin_site_image_path(@site, image),:remote => true, 'data-target' => "#myModal" %>
					<%= link_to '<i class="icon-nav menu-close"></i>'.html_safe, remove_admin_site_image_path(@site, image, gallery_id:@gallery.id), method: :post, :remote => true %>
				</div>

			</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/admin/galleries/edit.html.erb
<%= render 'form' %>

app/views/admin/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.name %></td>
    <td><%= link_to 'Show', admin_site_gallery_path(@site, gallery) %></td>
    <td><%= link_to 'Edit', edit_admin_site_gallery_path(@site, gallery) %></td>
    <td><%= link_to 'Destroy', admin_site_gallery_path(@site, gallery), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_admin_site_gallery_path %>

app/views/admin/galleries/show.js.erb
$('#pjax-container').html('<%= escape_javascript(render :partial => "right") %>');
document.title = "<%= escape_javascript("#{@gallery.name}") %>";
$('#hidden_field').html('<input id="gallery_id" name="gallery_id" type="hidden" value="' + $('#sortable').data('gallery_id') + '">');
$('#new_image').fileupload('enable');
resize();
galleryInit();


   