config/routes.rb
FolioApp::Application.routes.draw do

  namespace :admin do
    resources :sites do
      member do
        post 'sort'
        post 'update_elements'
      end
      resources :previews
      resources :images do
        collection do
          post 'sort'
          post 'move_images'
        end
        member do
          post 'remove'
        end
      end
      
      resources :galleries do
        collection do
          post 'sort'
        end
      end
      resources :gallery_pages 
      resources :pages do
        member do
          post 'add_text_element'
        end
      end
      resources :links 
      resources :elements do
        member do
          post 'remove'
        end
      end
      resources :folders
      resource :setting, only: [:show]
      resource :header, only: [:show] do
        member do
          post 'add_text_element'
        end
      end
      resource :homepage, only: [:show]
      resource :template do
        collection do
          post 'update_template'
        end
      end
      resources :layouts
    end
  end

  resources :sites, only: [:show], :controller => "homepages" do
    resources :pages, only: [:show]  
    resources :galleries, only: [:show] 
  end

  devise_for :users
  match 'users' => 'users#index'
  match 'about' => "static_pages#about"
  root :to => "static_pages#home"

end

app/models/homepage.rb
# == Schema Information
#
# Table name: homepages
#
#  id         :integer          not null, primary key
#  name       :string(255)      default("Home")
#  site_id    :integer
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Homepage < ActiveRecord::Base
	belongs_to :site
	has_one :nav_item, :as =>:navable, :dependent => :destroy
	has_many :elements, :dependent => :destroy
  
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name
  attr_accessible :name, :site_id, :slug
end

app/controllers/admin/homepages_controller.rb
class Admin::HomepagesController < ApplicationController
	before_filter :authenticate_user!
  before_filter :get_site

  def show
    @image = Image.new
    @homepage = @site.homepage
    @nav_items = @site.nav_items.includes(:navable).nav_scope
    @gallery_items = @site.nav_items.includes(:navable).gallery_scope
    
    if request.headers['X-PJAX']
      puts "pjax hit"
      render :layout => false
    else 
      respond_to do |format| 
        format.html { render layout: 'admin_content' }
        format.js {}
      end
    end

    # respond_to do |format| 
    #   format.html { render layout: 'admin_content' }
    #   format.js {}
    # end
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
	def show
		@site = Site.find(params[:id])
		@homepage = @site.homepage
  	@nav_items = @site.nav_items.includes(:navable).nav_scope
  	render layout: 'site'
	end
end

app/helpers/admin/homepages_helper.rb
module Admin::HomepagesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/admin/homepages/_right.html.erb
<div class="right-panel">
	<div class="navbar secondary-navbar">
		<ul class="nav">
			<li class="icon_button">
				<a href="#" id="caret">
					<div>
						<div class="icon caret-left"></div>
					</div>
				</a>
			</li>
			<li class="divider-vertical"></li>
		</ul>
		<div class="left secondary-nav-text"> <%= @homepage.name %></div>
		<ul class="nav pull-right">
			<li class="divider-vertical"></li>
			<li  class="dropdown icon_button">
				<a href="#" id="add_element" class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" data-original-title="Add Element"><div class="icon add"></div> </a>
				<ul class="dropdown-menu">
					<li><a href="#">Text Element</a></li>
					<li><a href="#">Image Element</a></li>
				</ul>
			</li>   
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<%= link_to site_path(@site) do %>
					<div id="view" class="" rel="tooltip" data-original-title="View Site">
						<div class="icon view"></div>
					</div>
				<% end %>
			</li>
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<a href="#" class="" rel="tooltip" rel="tooltip" data-original-title="Save">
					<div id="save" class="" >
						<div class="icon save"></div>
					</div>
				</a>
			</li>
			<li class="divider-vertical"></li>
			<li class="icon_button">
				<a href="#" class="" rel="tooltip" data-original-title="Trash" >
					<div id="trash" class="">
						<div class="icon trash"></div>
					</div>
				</a>
			</li>
		</ul>
	</div>
	<div class="right-inner">
		<h1><%= @homepage.name %></h1>
	</div>
</div>