config/routes.rb
FolioApp::Application.routes.draw do

  namespace :admin do
    resources :sites do
      member do
        post 'sort'
        post 'update_elements'
      end
      resources :previews
      resources :images do
        collection do
          post 'sort'
          post 'move_images'
        end
        member do
          post 'remove'
        end
      end
      
      resources :galleries do
        collection do
          post 'sort'
        end
      end
      resources :gallery_pages 
      resources :pages do
        member do
          post 'add_text_element'
        end
      end
      resources :links 
      resources :elements do
        member do
          post 'remove'
        end
      end
      resources :folders
      resource :setting, only: [:show]
      resource :header, only: [:show] do
        member do
          post 'add_text_element'
        end
      end
      resource :homepage, only: [:show]
      resource :template do
        collection do
          post 'update_template'
        end
      end
      resources :layouts
    end
  end

  resources :sites, only: [:show], :controller => "homepages" do
    resources :pages, only: [:show]  
    resources :galleries, only: [:show] 
  end

  devise_for :users
  match 'users' => 'users#index'
  match 'about' => "static_pages#about"
  root :to => "static_pages#home"

end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  caption    :string(255)
#  image_file :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  site_id    :integer
#

class Image < ActiveRecord::Base
	belongs_to :site
	has_one :element, :as =>:child, :dependent => :destroy
  has_many :gallery_assignments, :dependent => :destroy
  has_many :galleries, :through => :gallery_assignments
  attr_accessible :caption, :image_file, :name
  mount_uploader :image_file, ImageFileUploader
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  before_filter :authenticate_user!
	before_filter :get_site

  def index

    @images = @site.images
    @image = Image.new
    @page = Page.new
    # @nav_items = @site.nav_items.includes([:navable, :parent, :children]).pos
    @nav_items = @site.nav_items.includes(:navable).nav_scope
    @gallery_items = @site.nav_items.includes(:navable).gallery_scope
    if request.headers['X-PJAX']
      render :layout => false
    else 
      respond_to do |format| 
        format.html { render layout: 'admin_content' }
        format.js {}
      end
    end
  end

  def show
    @image = @site.images.find(params[:id])
  end

  def new
    @image = Image.new
    if params[:page_id]
      @page_id = params[:page_id]
    elsif params[:header_id]
      @header_id = params[:header_id]
    end
      
  end

  def edit
    @image = @site.images.find(params[:id])
    render :layout => false
  end

  def create

    @image = @site.images.new(params[:image])
    
    if @image.save
      if params[:gallery_id]
        @gallery = Gallery.find(params[:gallery_id])
        # Add 1 to the position of each gallery_assignment of the gallery
        @gallery.gallery_assignments.each do |gallery_assignment|
          gallery_assignment.position = gallery_assignment.position + 1
          gallery_assignment.save
        end
        # Create new gallery_assignment
        ga = @gallery.gallery_assignments.new(image_id:@image.id)
        ga.save

        render :nothing => true
      elsif params[:page_id]
        p = Page.find(params[:page_id])       
        p.elements.create(child:@image, top:100, left:100, width:200, height:200) 
        redirect_to :back

      elsif params[:header_id]
        h = Header.find(params[:header_id])       
        h.elements.create(child:@image, top:100, left:100, width:200, height:200) 
        redirect_to :back
      end
      
    end
  end

  def update
    @image = @site.images.find(params[:id])
      if @image.update_attributes(params[:image])
        redirect_to admin_site_image_path(@site,@image)#, notice: 'Image was successfully updated.' 
      else
        render action: "edit" 
      end
  end

  def destroy
    @image = @site.images.find(params[:id])
    @image.destroy

    redirect_to :back

  end

  def remove
    gallery = Gallery.find(params[:gallery_id])
    @image = @site.images.find(params[:id])
    ga = GalleryAssignment.find_by_gallery_id_and_image_id(gallery.id, @image.id)
    ga.destroy

    respond_to do |format|
      format.js {}
    end

  end

  def sort
    
    gallery = Gallery.find(params[:gallery_id])
    array = params[:images].gsub('image[]=', '').split('&')
    
    array.each_with_index do |id, index|
      image = Image.find(id.to_i)
      ga = GalleryAssignment.find_by_gallery_id_and_image_id(gallery.id, image.id)
      ga.position = index
      ga.save
    end

     render :nothing => true
  end

  def move_images
    gallery = Gallery.find(params[:gallery_id].gsub('gallery_', '').to_i)
    array = params[:images].gsub('image_', '').split('&')
    array.map! { |id| id.to_i }

    
    # remove existing images if they already exist
    array2 = gallery.images.map { |item| item.id }
    array.keep_if { |n| !array2.include?(n) }

    unless array.length == 0
      # Add the length of the array to the position of each gallery_assignment of the gallery
      gallery.gallery_assignments.each do |gallery_assignment|
        gallery_assignment.position = gallery_assignment.position + array.length
        gallery_assignment.save
      end

      array.each_with_index do |id, index|
        image = Image.find(id.to_i)
        ga = gallery.gallery_assignments.new(image_id:image.id)
        ga.position = index
        ga.save
      end
    end

    render :nothing => true
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  before_filter :get_site
  # before_filter :get_gallery

  def index
    @images = @site.images

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  def show
    @image = @site.images.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  def edit
    @image = @site.images.find(params[:id])
  end

  def create
    @image = @site.images.new(params[:image])
    @gallery = Gallery.find(params[:gallery_id])

    if @image.save

      # Add 1 to the position of each gallery_assignment of the gallery
      @gallery.gallery_assignments.each do |gallery_assignment|
        gallery_assignment.position = gallery_assignment.position + 1
        gallery_assignment.save
      end

      # Create new gallery_assignment
      ga = @gallery.gallery_assignments.new(image_id:@image.id)
      ga.save

      redirect_to site_gallery_path(@site,@gallery), notice: 'Image was successfully created.'
    else
      redirect_to site_gallery_path(@site,@gallery), notice: 'Image was not saved.'
    end
  end

  def update
    @image = @site.images.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to site_image_path(@site,@image), notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image = @site.images.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  def sort
    
    gallery = Gallery.find(params[:gallery_id])
    array = params[:images].gsub('image[]=', '').split('&')
    
    array.each_with_index do |id, index|
      image = Image.find(id.to_i)
      ga = GalleryAssignment.find_by_gallery_id_and_image_id(gallery.id, image.id)
      ga.position = index
      ga.save
    end

     render :nothing => true
  end

  private

  def get_site 
    @site = Site.find(params[:site_id])
  end

  def get_gallery
    @gallery = Gallery.find(params[:id])
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/images/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Image</h3>
</div>

<%= form_for [:admin, @site, @image] do |f| %>
<div class="modal-body">
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>

  <div class="field">
    <%= f.label :image_file %><br />
    <%= f.file_field :image_file %>
  </div>

  <% if @page_id %>
    <%= hidden_field_tag :page_id, @page_id %>
  <% end %>

  <% if @header_id %>
    <%= hidden_field_tag :header_id, @header_id %>
  <% end %>
</div>

<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/admin/images/_right.html.erb
<div class="right-panel">
	<div class="navbar secondary-navbar">
		<ul class="nav">
			<li class="icon_button">
				<a href="#" id="caret">
					<div>
						<div class="icon caret-left"></div>
					</div>
				</a>
			</li>
			<li class="divider-vertical"></li>
		</ul>
		<div class="left secondary-nav-text"> All Images</div>
		<ul class="nav pull-right">

			<li class="divider-vertical"></li>
			<li class="icon_button">
				<a href="#" class="" rel="tooltip" data-original-title="Trash" >
					<div id="trash" class="">
						<div class="icon trash"></div>
					</div>
				</a>
			</li>
		</ul>
	</div>
	<div class="right-inner">
		
		<ul id="sortable" class="thumb_grid" data-move-images-url="<%= move_images_admin_site_images_path(@site) %>">
			<% @images.each do |image| %>
			<li id="image_<%= image.id %>" class="drop_allowed">
				<div class="thumbnail_border"></div>
				
				<div class="thumbnail">
					<%= image_tag image.image_file_url(:thumb).to_s %>
				</div>
				<div class="image_icons">
					<%= link_to '<i class="icon-nav menu-settings"></i>'.html_safe, edit_admin_site_image_path(@site, image),:remote => true, 'data-target' => "#myModal" %>
					<%= link_to '<i class="icon-nav menu-close"></i>'.html_safe, admin_site_image_path(@site, image), method: :delete, data: { confirm: 'Are you sure? This will remove the image from all galleries and lightboxes.' } %></div></li>
					<% end %>
				</ul>
			</div>
		</div>

app/views/admin/images/index.html.erb
<%= render 'right' %>

app/views/admin/images/new.html.erb
<%= render 'form' %>

app/views/admin/images/remove.js.erb
$('#image_<%= @image.id %>').remove();

app/views/admin/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @image.image_file_url(:medium).to_s %>

<%= link_to 'Edit', edit_admin_site_image_path(@site, @image) %> |
<%= link_to 'Back', admin_site_images_path %>